x-logging: &default-logging
  options:
    max-size: "100m"
    max-file: "5"
  driver: json-file

services:
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.9
    container_name: zookeeper
    networks:
      - eval-carbone
    volumes:
      - "numecoeval_zookeeper_data:/bitnami"
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
    logging: *default-logging
    restart: unless-stopped

  kafka:
    image: docker.io/bitnami/kafka:3.6
    container_name: kafka
    networks:
      - eval-carbone
    depends_on:
      - zookeeper
    volumes:
      - "numecoeval_kafka_data:/bitnami"
    environment:
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
    healthcheck:
      test: ["CMD-SHELL", "kafka-cluster.sh cluster-id --bootstrap-server localhost:9092"]
      interval: 5s
      timeout: 2s
      retries: 3
    logging: *default-logging
    restart: unless-stopped

  postgresdb:
    image: docker.io/postgres:15
    container_name: postgresdb
    networks:
      - eval-carbone
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    volumes:
      - "numecoeval_postgres_data:/var/lib/postgresql/data"
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d postgres'"]
      interval: 5s
      timeout: 10s
      retries: 3
    logging: *default-logging
    restart: unless-stopped

  api-rest-referentiels:
    image: ${REGISTRY_URL}/api-referentiel:${TAG}
    container_name: api-rest-referentiels
    networks:
      - eval-carbone
    depends_on:
      postgresdb:
        condition: service_healthy
    environment:
      SERVER_PORT: "8080"
      MANAGEMENT_SERVER_PORT: "8080"
      SPRING_JPA_HIBERNATE_DDL-AUTO: "update"
      SPRING_DATASOURCE_URL: "jdbc:postgresql://postgresdb:5432/postgres?reWriteBatchedInserts=true"
      SPRING_DATASOURCE_USERNAME: $POSTGRES_USER
      SPRING_DATASOURCE_PASSWORD: $POSTGRES_PASSWORD
      SPRING_SERVLET_MULTIPART_MAXREQUESTSIZE: "45MB"
      SPRING_SERVLET_MULTIPART_MAXFILESIZE: "10MB"
      SPRING_JPA_PROPERTIES_HIBERNATE_JDBC_BATCHSIZE: "1000"
      SPRING_JPA_PROPERTIES_HIBERNATE_ORDERINSERTS: "true"
      SPRING_JPA_SHOWSQL: "false"
      NUMECOEVAL_URLS_ALLOWED: "http://localhost,http://api-rest-referentiels,http://localhost:3000"
      LOGGING_LEVEL_ROOT: $LOGGING_LEVEL_ROOT
      LOGGING_LEVEL_ORG_SPRINGFRAMEWORK: $LOGGING_LEVEL_ORG_SPRINGFRAMEWORK
    logging: *default-logging
    restart: unless-stopped

  api-rest-expositiondonneesentrees:
    image: ${REGISTRY_URL}/api-expositiondonneesentrees:${TAG}
    container_name: api-rest-expositiondonneesentrees
    networks:
      - eval-carbone
    depends_on:
      postgresdb:
        condition: service_healthy
      api-rest-referentiels:
        condition: service_started
    environment:
      SERVER_PORT: "8080"
      MANAGEMENT_SERVER_PORT: "8080"
      NUMECOEVAL_KAFKA_TOPIC_MAX_MESSAGES_SIZE: "52428800"
      NUMECOEVAL_REFERENTIEL_SERVER_URL: "http://api-rest-referentiels:8080"
      SPRING_SERVLET_MULTIPART_MAXREQUESTSIZE: "45MB"
      SPRING_SERVLET_MULTIPART_MAXFILESIZE: "10MB"
      SPRING_DATASOURCE_URL: "jdbc:postgresql://postgresdb:5432/postgres?reWriteBatchedInserts=true"
      SPRING_DATASOURCE_USERNAME: $POSTGRES_USER
      SPRING_DATASOURCE_PASSWORD: $POSTGRES_PASSWORD
      SPRING_JPA_PROPERTIES_HIBERNATE_GENERATESTATISTICS: "true"
      SPRING_JPA_PROPERTIES_HIBERNATE_ORDERINSERTS: "true"
      SPRING_JPA_PROPERTIES_HIBERNATE_JDBC_BATCHSIZE: "1000"
      SPRING_JPA_SHOWSQL: "false"
      NUMECOEVAL_URLS_ALLOWED: "http://localhost,http://api-rest-expositiondonneesentrees,http://localhost:3000"
      LOGGING_LEVEL_ROOT: $LOGGING_LEVEL_ROOT
      LOGGING_LEVEL_ORG_SPRINGFRAMEWORK: $LOGGING_LEVEL_ORG_SPRINGFRAMEWORK
      NUMECOEVAL_CALCULS_SERVER_URL: "http://api-event-calculs:8080"
    logging: *default-logging
    restart: unless-stopped

  api-event-donneesentrees:
    image: ${REGISTRY_URL}/api-event-donneesentrees:${TAG}
    container_name: api-event-donneesentrees
    networks:
      - eval-carbone
    depends_on:
      kafka:
        condition: service_healthy
      postgresdb:
        condition: service_healthy
      api-rest-expositiondonneesentrees:
        condition: service_started
    environment:
      SERVER_PORT: "8080"
      MANAGEMENT_SERVER_PORT: "8080"
      SPRING_KAFKA_BOOTSTRAPSERVERS: "kafka:9092"
      SPRING_DATASOURCE_URL: "jdbc:postgresql://postgresdb:5432/postgres?reWriteBatchedInserts=true"
      SPRING_DATASOURCE_USERNAME: $POSTGRES_USER
      SPRING_DATASOURCE_PASSWORD: $POSTGRES_PASSWORD
      LOGGING_LEVEL_ROOT: $LOGGING_LEVEL_ROOT
      LOGGING_LEVEL_ORG_SPRINGFRAMEWORK: $LOGGING_LEVEL_ORG_SPRINGFRAMEWORK
    logging: *default-logging
    restart: unless-stopped

  api-event-calculs:
    image: ${REGISTRY_URL}/api-event-calculs:${TAG}
    container_name: api-event-calculs
    networks:
      - eval-carbone
    depends_on:
      kafka:
        condition: service_healthy
      postgresdb:
        condition: service_healthy
    environment:
      SERVER_PORT: "8080"
      MANAGEMENT_SERVER_PORT: "8080"
      NUMECOEVAL_URLS_ALLOWED: "http://localhost,http://api-event-calculs,http://localhost:3000"
      NUMECOEVAL_REFERENTIELS_URL: "http://api-rest-referentiels:8080"
      SPRING_KAFKA_BOOTSTRAPSERVERS: "kafka:9092"
      SPRING_DATASOURCE_URL: "jdbc:postgresql://postgresdb:5432/postgres?reWriteBatchedInserts=true"
      SPRING_DATASOURCE_USERNAME: $POSTGRES_USER
      SPRING_DATASOURCE_PASSWORD: $POSTGRES_PASSWORD
      LOGGING_LEVEL_ROOT: $LOGGING_LEVEL_ROOT
      LOGGING_LEVEL_ORG_SPRINGFRAMEWORK: $LOGGING_LEVEL_ORG_SPRINGFRAMEWORK
    logging: *default-logging
    restart: unless-stopped

networks:
  eval-carbone:
    driver: bridge
    name: num-eco-eval

volumes:
  numecoeval_zookeeper_data:
    driver: local
  numecoeval_kafka_data:
    driver: local
  numecoeval_postgres_data:
    driver: local
