services:
  zookeeper:
    extends:
      file: infra/roles/backend/files/docker-compose.yml
      service: zookeeper
    networks:
      - eval-carbone
    ports:
      - 2181:2181

  kafka:
    extends:
      file: infra/roles/backend/files/docker-compose.yml
      service: kafka
    networks:
      - eval-carbone
    ports:
      - 9092:9092

  postgresdb:
    extends:
      file: infra/roles/backend/files/docker-compose.yml
      service: postgresdb
    networks:
      - eval-carbone
    ports:
      - 5432:5432

  api-rest-referentiels:
    extends:
      file: infra/roles/backend/files/docker-compose.yml
      service: api-rest-referentiels
    networks:
      - eval-carbone
    ports:
      - ${PORT_PREFIX}8080:8080

  api-rest-expositiondonneesentrees:
    extends:
      file: infra/roles/backend/files/docker-compose.yml
      service: api-rest-expositiondonneesentrees
    networks:
      - eval-carbone
    ports:
      - ${PORT_PREFIX}8081:8080

  api-event-donneesentrees:
    extends:
      file: infra/roles/backend/files/docker-compose.yml
      service: api-event-donneesentrees
    networks:
      - eval-carbone
    ports:
      - ${PORT_PREFIX}8083:8080

  api-event-calculs:
    extends:
      file: infra/roles/backend/files/docker-compose.yml
      service: api-event-calculs
    networks:
      - eval-carbone
    ports:
      - ${PORT_PREFIX}8085:8080

networks:
  eval-carbone:
    driver: bridge
    name: num-eco-eval

volumes:
  numecoeval_zookeeper_data:
    driver: local
  numecoeval_kafka_data:
    driver: local
  numecoeval_postgres_data:
    driver: local
