services:
  nginx-proxy:
    container_name: nginx-proxy
    image: nginxproxy/nginx-proxy
    networks:
      - eval-carbone
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - vhost:/etc/nginx/vhost.d
      - ./eval-carbone-sih.esante.gouv.fr_location:/etc/nginx/vhost.d/eval-carbone-sih.esante.gouv.fr_location
      - ./eval-carbone-sih.esante.gouv.fr.crt:/etc/nginx/certs/eval-carbone-sih.esante.gouv.fr.crt
      - ./eval-carbone-sih.esante.gouv.fr.key:/etc/nginx/certs/eval-carbone-sih.esante.gouv.fr.key
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"

networks:
  eval-carbone:
    name: num-eco-eval
    external: true

volumes:
  certs:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/etc/nginx/certs'
  vhost:
  html:
