- name: Copy docker-compose
  become: false
  copy:
    src: docker-compose.yml
    dest: docker-compose-reverse-proxy.yml

- name: Create certs directory
  file:
    path: /etc/nginx/certs
    state: directory

- name: Copy Nginx config
  copy:
    src: eval-carbone-sih.esante.gouv.fr_location
    dest: eval-carbone-sih.esante.gouv.fr_location

- name: Copy .crt file
  copy:
    src: eval-carbone-sih.esante.gouv.fr.crt
    dest: eval-carbone-sih.esante.gouv.fr.crt

- name: Copy .key file
  copy:
    src: eval-carbone-sih.esante.gouv.fr.key
    dest: eval-carbone-sih.esante.gouv.fr.key

- name: Start Nginx
  community.docker.docker_compose_v2:
    files: docker-compose-reverse-proxy.yml
    project_src: .
